version: "3"
services:
  api:
    image: msg:latest
    build:
      dockerfile: ./Api/Dockerfile
    ports:
      - "8010:8080"
    networks:
      - backend


  mysql:
    image: mysql:latest
    restart: always
    command:
      - --lower_case_table_names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    container_name: mysql_msg
    ports:
      - "3301:3306"
    environment:
      - MYSQL_DATABASE=msg
      - MYSQL_ROOT_PASSWORD=1234
      - TZ = Asia/Seoul
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - C:\Users\user\Desktop\Back\docker\msg:/var/lib/mysql

    networks:
      - backend
networks:
  backend:
    driver: bridge
