spring:
  jwts:
    secret:${JWT_SECRET}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      format_sql: true
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    url: jdbc:mysql://localhost:3301/MSG?userSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${ROOT_PWD}

jwt:
  perfix: ${JWT_PERFIX:Bearer}
  header: ${JWT_HEADER:Authorization}
  secret: ${JWT_SECRET:whsrudgksmsrnralsdufjqneoxhdfudekdtjsdlsdbflqmffkel}
  expiration: ${JWT_EXPIRATION:86400000}