spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      format_sql: true
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://localhost:3305/MSG?userSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${ROOT_PWD}

  jwt:
    secret: ${JWT_SECRET}